apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-world-nginx
  name: hello-world-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-world-nginx
    spec:
      containers:
      - image: hello-world-nginx
        name: hello-world-nginx
        imagePullPolicy: Never 
        resources: {}
status: {}
